appendonly yes
appendfsync everysec
save 900 1
save 300 10
save 60 10000
lazyfree-lazy-eviction yes
lazyfree-lazy-expire yes
lazyfree-lazy-server-del yes
maxmemory-policy noeviction
tcp-keepalive 60
dir /data
